### ISSUE TITLE
Style problems in the panel

### ISSUE THREAD

**Issue by irina060981** [alpheios-project/components#441]
@balmas and @kirlat ,
I have noticed that on this site - http://www.thelatinlibrary.com/cicero/legagr1.shtml
panel to right icon is not visible and is not clickable.

There is some problems with layout. I wasn't able to find a click solution.
So creating an issue.

![image](https://user-images.githubusercontent.com/12377640/56181744-34be9200-6052-11e9-9da9-9203ebb118ba.png)

Also checkboxs here are not rendered at all (height = 0)
![image](https://user-images.githubusercontent.com/12377640/56189242-ccc87580-606a-11e9-8514-a3b5e453d73c.png)

**Comment by balmas** [comment]
Could it be fixed by the fix for  #439 ?

**Comment by irina060981** [comment]
I have checked with the webextension and components after #439 - it is not fixed:
![image](https://user-images.githubusercontent.com/12377640/56263113-ffcf3f80-6124-11e9-82b8-0a17cb1e0f5a.png)

**Comment by kirlat** [comment]
I can reproduce this problem in the latest version of webextension in Chrome. Will work on a fix.

**Comment by balmas** [comment]
Can be tested in 3.0.0.29 https://github.com/alpheios-project/webextension/tree/qa-3.0.0.29/dist and in Dropbox for Safari

**Comment by monzug** [comment]
Looks good in 3.0.0.29, both Chrome and Firefox.
