### ISSUE TITLE
We don't override !important styles from the underlying page

### ISSUE THREAD

**Issue by monzug** [alpheios-project/components#760]
Options: when on small, the large option is truncated in loebclassics. 
see screenshot
![large is truncated](https://user-images.githubusercontent.com/41396793/63350538-9e65ea00-c32b-11e9-8552-fa1229b03d59.JPG)

**Comment by balmas** [comment]
maybe related to problems noted in #750

**Comment by irina060981** [comment]
I have merged all styles changes with https://github.com/alpheios-project/components/pull/763
And it is not reproducable for me.

@balmas,  I suggest to retest it with the final components

**Comment by balmas** [comment]
I can still reproduce it in Loeb Classics, but not in the Latin Library. I think it's the same issue reported in #750.

**Comment by balmas** [comment]
the problem here is that if a page applies an !important flag to their styles, ours will be overridden.

See comments at https://github.com/alpheios-project/components/issues/750#issuecomment-523420775

**Comment by balmas** [comment]
As @irina060981 notes in the other issue, using an !important flag is not good practice. We do however use this in Safari because it is needed their for other reasons. 

I'm not sure if we should just do the same for Chrome and FF or not. Thinking about it a little.

**Comment by balmas** [comment]
@kirlat do you have any thoughts about this?  Since we should be namespacing all of our styles, I'm wondering if it would just make sense to use the safari build of the css, with the !important flag added, for all browsers.

Also, I was trying to double-check the compiled style-components.css to make sure everything is namespaced, and I came across a strange line that I can't find the source of. It looks like it's combining a variety of settings here, and I can't anywhere find the source of fieldset[disabled]. (this is from https://github.com/alpheios-project/components/blob/master/dist/style/style-components.css#L1323). Does something about this look off to both of you?

```
fieldset[disabled] .multiselect{pointer-events:none}.multiselect__spinner{position:absolute;right:1px;top:1px;width:48px;height:35px;background:#fff;display:block}.multiselect__spinner:after,.multiselect__spinner:before{position:absolute;content:"";top:50%;left:50%;margin:-8px 0 0 -8px;width:16px;height:16px;border-radius:100%;border:2px solid transparent;border-top-color:#41b883;box-shadow:0 0 0 1px transparent}.multiselect__spinner:before{animation:spinning 2.4s cubic-bezier(.41,.26,.2,.62);animation-iteration-count:infinite}.multiselect__spinner:after{animation:spinning 2.4s cubic-bezier(.51,.09,.21,.8);animation-iteration-count:infinite}.multiselect__loading-enter-active,.multiselect__loading-leave-active{transition:opacity .4s ease-in-out;opacity:1}.multiselect__loading-enter,.multiselect__loading-leave-active{opacity:0}.multiselect,.multiselect__input,.multiselect__single{font-family:inherit;font-size:16px;-ms-touch-action:manipulation;touch-action:manipulation}.multiselect{box-sizing:content-box;display:block;position:relative;width:100%;min-height:40px;text-align:left;color:#35495e}.multiselect *{box-sizing:border-box}.multiselect:focus{outline:none}.multiselect--disabled{background:#ededed;pointer-events:none;opacity:.6}.multiselect--active{z-index:50}.multiselect--active:not(.multiselect--above) .multiselect__current,.multiselect--active:not(.multiselect--above) .multiselect__input,.multiselect--active:not(.multiselect--above) .multiselect__tags{border-bottom-left-radius:0;border-bottom-right-radius:0}.multiselect--active .multiselect__select{transform:rotate(180deg)}.multiselect--above.multiselect--active .multiselect__current,.multiselect--above.multiselect--active .multiselect__input,.multiselect--above.multiselect--active .multiselect__tags{border-top-left-radius:0;border-top-right-radius:0}.multiselect__input,.multiselect__single{position:relative;display:inline-block;min-height:20px;line-height:20px;border:none;border-radius:5px;background:#fff;padding:0 0 0 5px;width:100%;transition:border .1s ease;box-sizing:border-box;margin-bottom:8px;vertical-align:top}.multiselect__input:-ms-input-placeholder{color:#35495e}.multiselect__input::placeholder{color:#35495e}.multiselect__tag~.multiselect__input,.multiselect__tag~.multiselect__single{width:auto}.multiselect__input:hover,.multiselect__single:hover{border-color:#cfcfcf}.multiselect__input:focus,.multiselect__single:focus{border-color:#a8a8a8;outline:none}.multiselect__single{padding-left:5px;margin-bottom:8px}.multiselect__tags-wrap{display:inline}.multiselect__tags{min-height:40px;display:block;padding:8px 40px 0 8px;border-radius:5px;border:1px solid #e8e8e8;background:#fff;font-size:14px}.multiselect__tag{position:relative;display:inline-block;padding:4px 26px 4px 10px;border-radius:5px;margin-right:10px;color:#fff;line-height:1;background:#41b883;margin-bottom:5px;white-space:nowrap;overflow:hidden;max-width:100%;text-overflow:ellipsis}.multiselect__tag-icon{cursor:pointer;margin-left:7px;position:absolute;right:0;top:0;bottom:0;font-weight:700;font-style:normal;width:22px;text-align:center;line-height:22px;transition:all .2s ease;border-radius:5px}.multiselect__tag-icon:after{content:"\D7";color:#266d4d;font-size:14px}.multiselect__tag-icon:focus,.multiselect__tag-icon:hover{background:#369a6e}.multiselect__tag-icon:focus:after,.multiselect__tag-icon:hover:after{color:#fff}.multiselect__current{min-height:40px;overflow:hidden;padding:8px 30px 0 12px;white-space:nowrap;border-radius:5px;border:1px solid #e8e8e8}.multiselect__current,.multiselect__select{line-height:16px;box-sizing:border-box;display:block;margin:0;text-decoration:none;cursor:pointer}.multiselect__select{position:absolute;width:40px;height:38px;right:1px;top:1px;padding:4px 8px;text-align:center;transition:transform .2s ease}.multiselect__select:before{position:relative;right:0;top:65%;color:#999;margin-top:4px;border-color:#999 transparent transparent;border-style:solid;border-width:5px 5px 0;content:""}.multiselect__placeholder{color:#adadad;display:inline-block;margin-bottom:10px;padding-top:2px}.multiselect--active .multiselect__placeholder{display:none}.multiselect__content-wrapper{position:absolute;display:block;background:#fff;width:100%;max-height:240px;overflow:auto;border:1px solid #e8e8e8;border-top:none;border-bottom-left-radius:5px;border-bottom-right-radius:5px;z-index:50;-webkit-overflow-scrolling:touch}.multiselect__content{list-style:none;display:inline-block;padding:0;margin:0;min-width:100%;vertical-align:top}.multiselect--above .multiselect__content-wrapper{bottom:100%;border-bottom-left-radius:0;border-bottom-right-radius:0;border-top-left-radius:5px;border-top-right-radius:5px;border-bottom:none;border-top:1px solid #e8e8e8}.multiselect__content::webkit-scrollbar{display:none}.multiselect__element{display:block}.multiselect__option{display:block;padding:12px;min-height:40px;line-height:16px;text-decoration:none;text-transform:none;vertical-align:middle;position:relative;cursor:pointer;white-space:nowrap}.multiselect__option:after{top:0;right:0;position:absolute;line-height:40px;padding-right:12px;padding-left:20px;font-size:13px}.multiselect__option--highlight{background:#41b883;outline:none;color:#fff}.multiselect__option--highlight:after{content:attr(data-select);background:#41b883;color:#fff}.multiselect__option--selected{background:#f3f3f3;color:#35495e;font-weight:700}.multiselect__option--selected:after{content:attr(data-selected);color:silver}.multiselect__option--selected.multiselect__option--highlight{background:#ff6a6a;color:#fff}.multiselect__option--selected.multiselect__option--highlight:after{background:#ff6a6a;content:attr(data-deselect);color:#fff}.multiselect--disabled .multiselect__current,.multiselect--disabled .multiselect__select{background:#ededed;color:#a6a6a6}.multiselect__option--disabled{background:#ededed!important;color:#a6a6a6!important;cursor:text;pointer-events:none}.multiselect__option--group{background:#ededed;color:#35495e}.multiselect__option--group.multiselect__option--highlight{background:#35495e;color:#fff}.multiselect__option--group.multiselect__option--highlight:after{background:#35495e}.multiselect__option--disabled.multiselect__option--highlight{background:#dedede}.multiselect__option--group-selected.multiselect__option--highlight{background:#ff6a6a;color:#fff}.multiselect__option--group-selected.multiselect__option--highlight:after{background:#ff6a6a;content:attr(data-deselect);color:#fff}.multiselect-enter-active,.multiselect-leave-active{transition:all .15s ease}.multiselect-enter,.multiselect-leave-active{opacity:0}.multiselect__strong{margin-bottom:8px;line-height:20px;display:inline-block;vertical-align:top}[dir=rtl] .multiselect{text-align:right}[dir=rtl] .multiselect__select{right:auto;left:1px}[dir=rtl] .multiselect__tags{padding:8px 8px 0 40px}[dir=rtl] .multiselect__content{text-align:right}[dir=rtl] .multiselect__option:after{right:auto;left:0}[dir=rtl] .multiselect__clear{right:auto;left:12px}[dir=rtl] .multiselect__spinner{right:auto;left:1px}@keyframes spinning{0%{transform:rotate(0)}to{transform:rotate(2turn)}}
```

**Comment by kirlat** [comment]
I think we shall use `important!` with an extreme care and using it for every site will be an overkill. We're having problems with just a small number of sites that use `important!` for its elements without, probably, any valid reason. So I think our response must be as fine tuned as possible.

We had situations like that before. To fix them, we've added couple of `important` modifiers to our styles, usually accommodated with comments: see https://github.com/alpheios-project/components/blob/master/src/styles/_content.scss#L2-L3 for instance. 

To me, a sensible approach would be to stick to this practice. If some site overrides some button somewhere and we cannot fix this without using `important!`, lets add it for that particular element only along with the comment explaining its use. Hopefully, this will not happen too often. As a result, we'll have a more balanced stylesheet that will not go "all nuclear". What do you think about such a take on that?

**Comment by kirlat** [comment]
> (this is from https://github.com/alpheios-project/components/blob/master/dist/style/style-components.css#L1323)

This CSS comes from the Vue multiselect component we're using: https://github.com/shentao/vue-multiselect/blob/master/src/Multiselect.vue#L376-L378. It is located in `node_modules`.

**Comment by irina060981** [comment]
>To me, a sensible approach would be to stick to this practice. If some site overrides some button somewhere and we cannot fix this without using important!, lets add it for that particular element only along with the comment explaining its use. 

I believe it is not enough, because if we apply `!important` to our basic styles, we would be to add it to all our styles that applied to buttons, inputs , selects and so on that are not basic.
Otherwise - our basic styles will overwrite our own styles.

I think that applying `!important` to all styles will make the following:

   - all our styles will overwrite all page's styles
   - we won't be able to use meaningful `important` flag for our styles
   - we would need to add important to all inline styles

It will make our code less flexible, but we should solve the problem with consistent layout among sites.
Or we could agree with incosistent layout on some sites with rough ignoring web standards.

I think that the second variant.


>https://github.com/alpheios-project/components/blob/master/dist/style/style-components.css#L1323). Does something about this look off to both of you?

@balmas, it is from `vue-multiselect` package

```
.multiselect__spinner {
  position: absolute;
  right: 1px;
  top: 1px;
  width: 48px;
  height: 35px;
  background: #fff;
  display: block;
}
```

**Comment by balmas** [comment]
Re the multiselect styles --- ok, I didn't realize we were getting styles from node_modules. That's a bit of a bummer because it's not namespaced, but it's okay.

**Comment by balmas** [comment]
re the !important flag on the styles, ok, let's leave this for now, and accept that the display will not be perfect on some sites.
