### ISSUE TITLE
Refactoring of the popup: no space in personsing + alignment

### ISSUE THREAD

**Issue by monzug** [alpheios-project/components#848]
there is no space between person and sing (see screenshot)
also the alignment is messy in mobile

![pop-up-1](https://user-images.githubusercontent.com/41396793/68138255-3ff5e400-fef6-11e9-90fe-5d30eb9480f3.JPG)

**Comment by monzug** [comment]
mobile:
![IMG_4063](https://user-images.githubusercontent.com/41396793/68138636-e04c0880-fef6-11e9-9963-a0a74db68781.PNG)
![IMG_4062](https://user-images.githubusercontent.com/41396793/68138638-e04c0880-fef6-11e9-8546-1d9e914f64c1.PNG)

**Comment by monzug** [comment]
an other one in Safari
![Screen Shot 2019-11-05 at 4 20 58 PM](https://user-images.githubusercontent.com/41396793/68220731-8a578d80-ffe8-11e9-84b0-bef4d5a54abf.png)

**Comment by balmas** [comment]
will be fixed in the next build.

**Comment by balmas** [comment]
should be fixed in qa-3.0.3.88/components 1.4.6

**Comment by monzug** [comment]
lookup concurro, can we add a space between intransitive and 3rd conjugation?
in mobile, component 1.4.6 I can still see the personsing

**Comment by balmas** [comment]
oops I forgot to update the stylesheet in the texts environment. That should be working now, but I will look into adding the space in between the intransitive and 3rd conjugation.

**Comment by monzug** [comment]
Thanks!

**Comment by monzug** [comment]
would it be possible to improve this view?
![bizzare-popup](https://user-images.githubusercontent.com/41396793/68308015-2382b480-007a-11ea-8e4a-9a8a4c90825c.JPG)

**Comment by balmas** [comment]
probably :-)

**Comment by monzug** [comment]
Love your answer!

**Comment by balmas** [comment]
> would it be possible to improve this view?
> ![bizzare-popup](https://user-images.githubusercontent.com/41396793/68308015-2382b480-007a-11ea-8e4a-9a8a4c90825c.JPG)

this is actually the same as #221 I think.  We should fix it but the inflection grouping code is awful so probably not in the current incremental :-(

**Comment by balmas** [comment]
>space in between the intransitive and 3rd conjugation.

should be fixed in QA-3.0.3.89/components 1.4.7

**Comment by monzug** [comment]
concurro looks good and so does the text environment and Safari
